# Install required plugins
required_plugins = ["vagrant-hostsupdater"]
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
  end


Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "environment/app/provision.sh", privileged: false

    config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.network "private_network", ip: "192.168.10.100"
    web.hostsupdater.aliases = ["development.local"]
    web.vm.synced_folder ".", "/home/ubuntu/app"


end

    config.vm.define "mongo" do |mongo|
    mongo.vm.box = "ubuntu/xenial64"
    mongo.vm.network "private_network", ip: "192.168.10.101"
    mongo.hostsupdater.aliases = ["mongo.local"]
    mongo.vm.synced_folder ".", "/home/ubuntu/mongo"


end
end
